### ISSUE TITLE
unreliable, lost all my money.

### ISSUE THREAD

**Issue by Asterinos1** [Thodoris-Evangelakos/Stock-market-Reinforcement-Learning#1]
![st,small,507x507-pad,600x600,f8f8f8](https://github.com/Thodoris-Evangelakos/Stock-market-Reinforcement-Learning/assets/79656046/1e408e2e-6f7a-48e3-b4e5-5ea0bb60db06)

**Comment by Thodoris-Evangelakos** [comment]
Hello,

Please note that this algorithm is meant to simulate the effectiveness of the MW algorithm in the given scenario, and shouldn't be used in an actual day-trading scheme. The test results will probably not be replicable in an actual market since in real life we're dealing with many more variables than in the theoretical scenario. If you have any more questions, please reply here, or forward them to @vsamtuc. Either one of us would be glad to help you out at our earliest convenience.

Best regards,
Thodoris Evangelakos

**Comment by Asterinos1** [comment]
It is called "miss leading advertisement" not to include such notices in your product. Therefore I would like to request a complete compensation for my loses.

**Comment by Thodoris-Evangelakos** [comment]
According to the license under which the software is presented as is, with no legal liability for the developer. I kindly suggest that you refer to the README file for further information.
